baseURL = "https://icl-tdu-git.github.io/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "知的計算システム研究室 | 東京電機大学"
theme = "icl"
disableKinds = ["taxonomy", "term", "RSS"]

[[menu.main]]
  name = "Member"
  url = "/member/"
  weight = 2

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 3

[[menu.main]]
  name = "Theses"
  url = "/theses/"
  weight = 4
